# Generated by Django 4.2.4 on 2023-12-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_index', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sort_index',
            field=models.IntegerField(default=0),
        ),
    ]
